// Canonical AURA event names written to the Solana Memo Program.
export const AURA_SOLANA_EVENTS = {
  SURGE_DETECTED: 'SURGE_DETECTED',
  INTRUSION_DETECTED: 'INTRUSION_DETECTED',
  RELAY_TRIGGERED: 'RELAY_TRIGGERED',
  RELAY_OVERRIDE: 'RELAY_OVERRIDE',
  VOICE_COMMAND: 'VOICE_COMMAND',
  SYSTEM_FAULT: 'SYSTEM_FAULT',
  DEVICE_MINTED: 'DEVICE_MINTED',
} as const;

export type AuraSolanaEvent =
  (typeof AURA_SOLANA_EVENTS)[keyof typeof AURA_SOLANA_EVENTS];
