export const mockDevices = [
  {
    id: "1",
    user_id: "mock-user",
    name: "Main Security Gateway",
    device_token: "mock-gateway-token",
    firmware_version: "2.4.1",
    environment_type: "home",
    is_online: true,
    last_seen: new Date().toISOString(),
    voltage_threshold_min: 205,
    voltage_threshold_max: 245,
    surge_sensitivity: "high",
    location_label: "Main Gate",
    nft_mint_address: "9xQ1MockGatewayMint",
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "mock-user",
    name: "Living Room Camera",
    device_token: "mock-camera-token",
    firmware_version: "2.3.8",
    environment_type: "home",
    is_online: true,
    last_seen: new Date(Date.now() - 120000).toISOString(),
    voltage_threshold_min: 205,
    voltage_threshold_max: 240,
    surge_sensitivity: "medium",
    location_label: "Living Room",
    nft_mint_address: "4vJ9MockCameraMint",
    created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "mock-user",
    name: "Front Door Lock",
    device_token: "mock-lock-token",
    firmware_version: "2.4.0",
    environment_type: "home",
    is_online: true,
    last_seen: new Date(Date.now() - 300000).toISOString(),
    voltage_threshold_min: 205,
    voltage_threshold_max: 245,
    surge_sensitivity: "high",
    location_label: "Front Door",
    nft_mint_address: null,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "mock-user",
    name: "Garage Door Opener",
    device_token: "mock-garage-token",
    firmware_version: "2.1.9",
    environment_type: "home",
    is_online: false,
    last_seen: new Date(Date.now() - 3600000).toISOString(),
    voltage_threshold_min: 205,
    voltage_threshold_max: 245,
    surge_sensitivity: "low",
    location_label: "Garage",
    nft_mint_address: null,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  }
];

export const mockThreats = [
  {
    id: "1",
    device_id: "1",
    zone_id: null,
    event_type: "intrusion",
    severity: "critical",
    voltage_at_event: 231,
    current_at_event: 6.3,
    action_taken: "Gate lockdown armed",
    relay_triggered: true,
    relay_channel: 1,
    auto_resolved: false,
    resolved_at: null,
    solana_signature: null,
    solana_slot: null,
    solana_confirmed: false,
    lisk_tx_id: null,
    lisk_confirmed: false,
    alerta_alert_id: "ALT-1001",
    alerta_status: "open",
    occurred_at: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "2",
    device_id: "2",
    zone_id: null,
    event_type: "surge",
    severity: "high",
    voltage_at_event: 258,
    current_at_event: 8.7,
    action_taken: "Relay isolated",
    relay_triggered: true,
    relay_channel: 2,
    auto_resolved: false,
    resolved_at: null,
    solana_signature: "9xQ1MockSignature",
    solana_slot: 28422012,
    solana_confirmed: true,
    lisk_tx_id: "lisk_mock_2048",
    lisk_confirmed: true,
    alerta_alert_id: "ALT-1000",
    alerta_status: "ack",
    occurred_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "3",
    device_id: "4",
    zone_id: null,
    event_type: "system_fault",
    severity: "low",
    voltage_at_event: null,
    current_at_event: null,
    action_taken: "Operator notified",
    relay_triggered: false,
    relay_channel: null,
    auto_resolved: true,
    resolved_at: new Date(Date.now() - 5400000).toISOString(),
    solana_signature: null,
    solana_slot: null,
    solana_confirmed: false,
    lisk_tx_id: null,
    lisk_confirmed: false,
    alerta_alert_id: "ALT-0999",
    alerta_status: "closed",
    occurred_at: new Date(Date.now() - 7200000).toISOString(),
  }
];

export const mockSensorReadings = [
  {
    id: "1",
    device_id: "1",
    voltage: 220,
    current_amps: 1.5,
    power_watts: 330,
    frequency: 60,
    power_factor: 0.94,
    energy_kwh: 18.2,
    is_anomaly: false,
    anomaly_score: null,
    recorded_at: new Date().toISOString()
  }
];

export const mockZones = [
  {
    id: "zone-1",
    device_id: "1",
    name: "Main Gate",
    zone_type: "critical",
    is_active: true,
    presence_detected: true,
    last_presence_at: new Date(Date.now() - 120000).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "zone-2",
    device_id: "1",
    name: "Server Room",
    zone_type: "restricted",
    is_active: true,
    presence_detected: false,
    last_presence_at: new Date(Date.now() - 7200000).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
];

export const mockNotifications = [
  {
    id: "1",
    user_id: "mock-user",
    threat_event_id: "1",
    type: "push",
    title: "Threat Detected!",
    body: "Human presence detected at front gate",
    is_read: false,
    delivered: true,
    created_at: new Date(Date.now() - 120000).toISOString()
  },
  {
    id: "2",
    user_id: "mock-user",
    threat_event_id: null,
    type: "in_app",
    title: "System Update Complete",
    body: "All security patches have been applied",
    is_read: true,
    delivered: true,
    created_at: new Date(Date.now() - 86400000).toISOString()
  }
];

export const mockReports = [
  {
    id: "1",
    device_id: "1",
    user_id: "mock-user",
    report_month: "2026-06",
    total_threats: 15,
    surges_blocked: 2,
    intrusions_detected: 3,
    relay_activations: 12,
    avg_voltage: 224.4,
    min_voltage: 211.2,
    max_voltage: 241.9,
    total_anomalies: 5,
    aura_health_score: 94,
    solana_events_logged: 15,
    lisk_tx_id: "lisk_mock_report_1",
    lisk_confirmed: true,
    alerta_alerts_count: 4,
    alerta_ack_rate: 0.92,
    pdf_url: null,
    generated_at: new Date().toISOString()
  },
  {
    id: "2",
    device_id: "1",
    user_id: "mock-user",
    report_month: "2026-05",
    total_threats: 32,
    surges_blocked: 8,
    intrusions_detected: 11,
    relay_activations: 28,
    avg_voltage: 222.1,
    min_voltage: 207.6,
    max_voltage: 246.4,
    total_anomalies: 19,
    aura_health_score: 91,
    solana_events_logged: 32,
    lisk_tx_id: "lisk_mock_report_2",
    lisk_confirmed: true,
    alerta_alerts_count: 12,
    alerta_ack_rate: 0.88,
    pdf_url: null,
    generated_at: new Date(Date.now() - 2592000000).toISOString()
  }
];
